/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/VoterLogin` | `/VoterLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/VoterRegister` | `/VoterRegister`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterDashboard` | `/VoterDashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterProfile` | `/VoterProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterResults` | `/VoterResults`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterVote` | `/VoterVote`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterVotes` | `/VoterVotes`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/VoterLogin` | `/VoterLogin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/VoterRegister` | `/VoterRegister`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterDashboard` | `/VoterDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterProfile` | `/VoterProfile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterResults` | `/VoterResults`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterVote` | `/VoterVote`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterVotes` | `/VoterVotes`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/VoterLogin${`?${string}` | `#${string}` | ''}` | `/VoterLogin${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/VoterRegister${`?${string}` | `#${string}` | ''}` | `/VoterRegister${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(voter)'}/VoterDashboard${`?${string}` | `#${string}` | ''}` | `/VoterDashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(voter)'}/VoterProfile${`?${string}` | `#${string}` | ''}` | `/VoterProfile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(voter)'}/VoterResults${`?${string}` | `#${string}` | ''}` | `/VoterResults${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(voter)'}/VoterVote${`?${string}` | `#${string}` | ''}` | `/VoterVote${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(voter)'}/VoterVotes${`?${string}` | `#${string}` | ''}` | `/VoterVotes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/VoterLogin` | `/VoterLogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/VoterRegister` | `/VoterRegister`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterDashboard` | `/VoterDashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterProfile` | `/VoterProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterResults` | `/VoterResults`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterVote` | `/VoterVote`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(voter)'}/VoterVotes` | `/VoterVotes`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
